"""add capacity check constraint and partial unique index on active registrations

Revision ID: eb3ffecfa287
Revises: faf98a7dedb6
Create Date: 2026-08-12 12:20:03.262779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb3ffecfa287'
down_revision: Union[str, Sequence[str], None] = 'faf98a7dedb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint(op.f('ck_events_capacity_positive'), 'events', 'capacity > 0')
    op.create_index('uq_registration_active', 'registrations', ['user_id', 'event_id'], unique=True, postgresql_where=sa.text("status IN ('PENDING_CONFIRMATION', 'CONFIRMED')"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_registration_active', table_name='registrations', postgresql_where=sa.text("status IN ('PENDING_CONFIRMATION', 'CONFIRMED')"))
    op.drop_constraint(op.f('ck_events_capacity_positive'), 'events', type_='check')
    # ### end Alembic commands ###
